codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

fixes:
  - "/home/runner/work/TicketBookingSystem/TicketBookingSystem/::"

ignore:
  - "BookingHub.Tests/**"
  - "**/Migrations/**"
