// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using BookingHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingHub.Infrastructure.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BookingHub.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("IdValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IdValue");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookingDate");

                    b.Property<Guid?>("FlightIdValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("FlightIdValue");

                    b.Property<int>("SeatCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SeatCount");

                    b.HasKey("IdValue");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("BookingHub.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("IdValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("IdValue");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AvailableSeats");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("DepartureDate");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FromLocation");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ToLocation");

                    b.HasKey("IdValue");

                    b.ToTable("Flights", (string)null);

                    b.HasData(
                        new
                        {
                            IdValue = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvailableSeats = 100,
                            DepartureDate = new DateTime(2027, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            From = "Delhi",
                            To = "Mumbai"
                        },
                        new
                        {
                            IdValue = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvailableSeats = 50,
                            DepartureDate = new DateTime(2027, 2, 1, 15, 30, 0, 0, DateTimeKind.Utc),
                            From = "Bangalore",
                            To = "Hyderabad"
                        });
                });

            modelBuilder.Entity("BookingHub.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("BookingHub.Domain.ValueObjects.BookingDestination", "Destination", b1 =>
                        {
                            b1.Property<Guid>("BookingIdValue")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Destination_Address");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Destination_Name");

                            b1.HasKey("BookingIdValue");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingIdValue");
                        });

                    b.Navigation("Destination");
                });
#pragma warning restore 612, 618
        }
    }
}
